plugins {
    id 'fabric-loom'
    id 'io.github.flemmli97.multiloader.changelog'
    id 'io.github.flemmli97.multiloader.common-convention'
}

archivesBaseName = rootProject.api_mod_id
version = "${project.minecraft_version}-${rootProject.api_version}-fabric"

loom {
    def aw = file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            vmArgs '-Dmixin.debug.export=true'
        }
        server {
            server()
        }
    }
}

ext {
    mod_meta = ["version": project.version, "mcversion": minecraft_version, "fabric_version": fabric_version]
}

configurations {
    remapCommon {
        canBeConsumed = true
    }
    remapCommonArtifact {
        canBeConsumed = true
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    compileOnly(project(':common-api'))
    compileOnly(project(path: ':common-api', configuration: 'commonDependency'))

    modImplementation include("io.github.flemmli97:lingua_bib:${lingua_bib}-fabric")
}

afterEvaluate {
    artifacts {
        configurations.named("compileClasspath").get().resolvedConfiguration.resolvedArtifacts.stream()
                .filter { artifact ->
                    configurations.named("remapCommon").get().incoming.dependencies.any {
                        artifact.moduleVersion.id.group.contains(it.group) && it.name == artifact.moduleVersion.id.name && it.version == artifact.moduleVersion.id.version
                    }
                }.each { add("remapCommonArtifact", it.file) }
    }
}

processResources {
    from(project(":common-api").sourceSets.main.resources)
    exclude '**/accesstransformer.cfg'
}

tasks.named('compileJava', JavaCompile) {
    source(project(":common-api").sourceSets.main.allSource)
}

tasks.named('sourcesJar', Jar) {
    from(project(":common-api").sourceSets.main.allSource)
    exclude '.cache'
}

tasks.register('cleanLocalPublish') {
    group = 'publishing'
    dependsOn ':common-api:clean', clean, publishToMavenLocal
    publishToMavenLocal.mustRunAfter ':common-api:clean', clean
}

tasks.register('cleanPublish') {
    group = 'publishing'
    dependsOn ':common-api:clean', clean, publish
    publish.mustRunAfter ':common-api:clean', clean
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact(remapJar)
            artifact(sourcesJar)
            artifactId api_mod_id
        }
    }
}