modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Flemmli97/SimpleQuests/issues"
[[mods]]
modId="simplequests"
version="${version}"
displayName="Simple Quests"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-quests-forge"
logoFile="icon.png"
authors="Flemmli97"
description='''Server sided questing'''
[[dependencies.simplequests]]
modId="minecraft"
mandatory=true
versionRange="[1.18,)"
ordering="NONE"
side="BOTH"
