plugins {
    id 'fabric-loom'
    id 'com.matthewprenger.cursegradle' version '1.4.0'
    id 'com.modrinth.minotaur' version '2.+'
    id 'io.github.flemmli97.multiloader.platform-fabric'
}

repositories {
    mavenCentral()
    maven {
        name = 'Fabric-Permission-API'
        url 'https://oss.sonatype.org/content/repositories/snapshots'
        content {
            includeGroup 'me.lucko'
        }
    }
}

dependencies {
    modImplementation "me.lucko:fabric-permissions-api:${rootProject.fabric_permissions_api}"

    modCompileOnly("dev.ftb.mods:ftb-ranks-fabric:${rootProject.ftb_ranks}")

    // Jar-Jar only in the remapped jar but we cant use that
    modRuntimeOnly "io.github.flemmli97:lingua_bib:${lingua_bib}-fabric"
    implementation(project(path: ":fabric-api", configuration: "namedElements"))
    include(project(path: ":fabric-api"))
}