buildscript {
    repositories {
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath "group": "com.github.johnrengelman", "name": "shadow", "version": "8.+"
    }
}

apply plugin: com.github.jengelman.gradle.plugins.shadow.ShadowPlugin

archivesBaseName = rootProject.api_base_name
version = project.minecraft_version + "-" + rootProject.api_version

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    forge {
        mixinConfigs = ["simplequests_api.mixins.json"]
    }
    forge {
        runs {
            client {
                vmArgs "-Dmixin.debug.export=true"
            }
            data {
                data()
                programArgs "--all", "--mod", "simplequests_api"
                programArgs "--output", project(":common-api").file("src/generated/resources").absolutePath
                property("ExampleGenPath", project.rootProject.file("Example-Datapack/Datapack").absolutePath)
            }
        }
    }
    mods {
        main { // to match the default mod generated for Forge
            sourceSet project.sourceSets.main
            sourceSet project(':common-api').sourceSets.main
        }
    }
}

ext {
    mod_meta = ["version": project.version, "loader_version": forge_loader_version, "mcversion": minecraft_version, "forge_version": forge_version]
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
    developmentForge.extendsFrom api
    shadowArtifact {
        canBeConsumed = true
        canBeResolved = true
    }
}

repositories {
    maven {
        name = "LinguaBib"
        url "https://gitlab.com/api/v4/projects/21830712/packages/maven"
    }
}

dependencies {
    forge "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    api(project(path: ":common-api", configuration: "namedElements")) { transitive false }
    shadowArtifact(project(path: ":common-api", configuration: "transformProductionForge"))

    modImplementation include("io.github.flemmli97:lingua_bib:${lingua_bib}-forge")
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand mod_meta
    }
    exclude '.cache'
}

shadowJar {
    exclude "fabric.mod.json"

    configurations = [project.configurations.shadowArtifact]
    archiveClassifier.set("dev-shadow")
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set("forge")
}

jar {
    archiveClassifier.set("dev")
}

sourcesJar {
    def commonSources = project(":common-api").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
    archiveClassifier.set("forge-sources")
}

artifacts {
    shadowArtifact(shadowJar)
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact(remapJar) {
                classifier null
                builtBy remapJar
            }
            artifact(sourcesJar) {
                classifier "sources"
                builtBy remapSourcesJar
            }
            artifactId project.archives_base_name
            version project.version + "-forge"
        }
    }

    repositories {
        maven {
            url "https://gitlab.com/api/v4/projects/21830712/packages/maven"
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("GPR_USER")
                password = project.findProperty("gpr.gitlab.token") ?: System.getenv("GPR_GITLAB_TOKEN")
            }
        }
    }
}