plugins {
    id "architectury-plugin" version "3.4-SNAPSHOT"
    id "dev.architectury.loom" version "1.4-SNAPSHOT" apply false
}

apply from: "https://raw.githubusercontent.com/Flemmli97/GradleScripts/arch-loom-v2/main.gradle"

tasks.register("publishAPI") {
    group = 'publishing'
    var clean = [":common-api:clean", ":fabric-api:clean", ":forge-api:clean"]
    dependsOn clean
    var publish = [":common-api:publish", ":fabric-api:publish", ":forge-api:publish"]
    publish.each { tasks.findByPath(it).mustRunAfter clean }
    dependsOn publish
}