name: Bug Report
description: Report a bug
body:
  - type: markdown
    attributes:
      value: |
        Please fill out this template to report a bug/crash!
        For the versions latest is NOT a valid version! If you write it your issue will be simply closed.
  - type: dropdown
    id: loader
    attributes:
      label: Modloader
      options:
        - Forge
        - Fabric
    validations:
      required: true
  - type: input
    id: mc_version
    attributes:
      label: Minecraft Version
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Modversion
      description: "Version of the mod"
    validations:
      required: true
  - type: input
    id: loader_version
    attributes:
      label: Modloader version
      description: "Version of forge/fabric(api)?"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the issue.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      value: 1. Step one
    validations:
      required: true
  - type: textarea
    id: mod_compat
    attributes:
      label: Mods that might affect the issue
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Use a paste site for the logs. If you copy paste the log in here you will be ignored!  \n
      Here are example links for those sites:  \n[gist](https://gist.github.com/)  \n[paste](https://paste.gg/)"
    validations:
      required: true