name: Suggestions
description: Suggest features using this
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestions
      description: What feature would you like to add?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: If you have a solution or implementation idea write it down here.