plugins {
    id 'io.github.flemmli97.multiloader.platform-common'
}

archivesBaseName = rootProject.api_mod_id
version = "${project.minecraft_version}-${rootProject.api_version}-common"

dependencies {
    implementation "io.github.flemmli97:lingua_bib:${lingua_bib}-common"
}

sourceSets.main.resources {
    srcDir "src/generated/resources"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId api_mod_id
        }
    }
}