apply from: "https://raw.githubusercontent.com/Flemmli97/GradleScripts/mc-architectury-fabric-neoforge/common.gradle"

repositories {
    mavenLocal()
    maven {
        name = "LinguaBib"
        url "https://gitlab.com/api/v4/projects/21830712/packages/maven"
    }
}


dependencies {
    modImplementation "io.github.flemmli97:lingua_bib:${lingua_bib}-common"
}

sourceSets.main.resources {
    srcDir "src/generated/resources"
}