modLoader="javafml"
loaderVersion="[${loader_version},)"
license="MIT"
issueTrackerURL="https://github.com/Flemmli97/SimpleQuests/issues"
[[mixins]]
config = "simplequests_api.mixins.json"
[[mods]]
modId="simplequests_api"
version="${version}"
displayName="Simple Quests API"
authors="Flemmli97"
description='''API handling questing'''
[[dependencies.simplequests_api]]
modId="minecraft"
type="required"
versionRange="[${mcversion},)"
ordering="NONE"
side="BOTH"
[[dependencies.simplequests_api]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"
