plugins {
    id 'net.neoforged.moddev'
    id 'io.github.flemmli97.multiloader.changelog'
    id 'io.github.flemmli97.multiloader.common-convention'
}

archivesBaseName = rootProject.api_mod_id
version = "${project.minecraft_version}-${rootProject.api_version}-neoforge"

neoForge {
    version = neoforge_version
    def at = project(":common-api").file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    validateAccessTransformers = true
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            disableIdeRun()
        }
        client {
            client()
            jvmArgument '-Dmixin.debug.export=true'
        }
        server {
            server()
        }
        var common = project(":common-api")
        data {
            data()
            programArguments.addAll "--all", "--mod", "simplequests_api"
            programArguments.addAll "--output", common.file("src/generated/resources").absolutePath
            systemProperty("ExampleGenPath", project.rootProject.file("Example-Datapack/Datapack").absolutePath)
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

ext {
    mod_meta = ["version": project.version, "loader_version": neo_loader_version, "mcversion": minecraft_version, "neoforge_version": neoforge_version]
}

repositories {
    maven {
        name = 'Fabric'
        url = uri('https://maven.fabricmc.net')
        content {
            includeGroupByRegex('net.fabricmc')
        }
    }
}

dependencies {
    compileOnly(project(':common-api'))
    compileOnly(project(path: ':common-api', configuration: 'commonDependency'))
    compileOnly(project(path: ':fabric-api', configuration: 'remapCommonArtifact'))

    jarJar(implementation("io.github.flemmli97:lingua_bib:${lingua_bib}-neoforge"))
}

processResources {
    from(project(":common-api").sourceSets.main.resources)
}

tasks.named('compileJava', JavaCompile) {
    source(project(":common-api").sourceSets.main.allSource)
}

tasks.named('sourcesJar', Jar) {
    from(project(":common-api").sourceSets.main.allSource)
    exclude '.cache'
}

tasks.register('cleanLocalPublish') {
    group = 'publishing'
    dependsOn ':common:clean', clean, publishToMavenLocal
    publishToMavenLocal.mustRunAfter ':common-api:clean', clean
}

tasks.register('cleanPublish') {
    group = 'publishing'
    dependsOn ':common-api:clean', clean, publish
    publish.mustRunAfter ':common-api:clean', clean
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact(jar)
            artifact(sourcesJar)
            artifactId api_mod_id
        }
    }
}