modLoader="javafml"
loaderVersion="[${loader_version},)"
license="All rights reserved"
issueTrackerURL="https://github.com/Flemmli97/SimpleQuests/issues"
[[mixins]]
config = "simplequests.mixins.json"
[[mods]]
modId="simplequests"
version="${version}"
displayName="Simple Quests"
displayURL="${homepage}"
logoFile="icon.png"
authors="Flemmli97"
description='''Server sided questing'''
[[dependencies.simplequests]]
modId="minecraft"
type="required"
versionRange="[${mcversion},)"
ordering="NONE"
side="BOTH"
[[dependencies.simplequests]]
modId="neoforge"
type="required"
versionRange = "[${neoforge_version},)"
ordering="NONE"
side="BOTH"
