plugins {
    id 'com.matthewprenger.cursegradle' version '1.4.0'
    id 'com.modrinth.minotaur' version '2.+'
    id 'io.github.flemmli97.multiloader.platform-neoforge'
}

neoForge {
    runs {
        var common = project(":common")
        data {
            data()
            programArguments.addAll "--all", "--mod", "simplequests"
            programArguments.addAll "--output", common.file("src/generated/resources").absolutePath
            systemProperty("ExampleGenPath", project.rootProject.file("Example-Datapack/Datapack").absolutePath)
        }
    }
}

dependencies {
    compileOnly("dev.ftb.mods:ftb-ranks-neoforge:${ftb_ranks}")

    // Jar-Jar only in the remapped jar but we cant use that
    runtimeOnly "io.github.flemmli97:lingua_bib:${lingua_bib}-neoforge"
    jarJar(implementation(project(path: ":neoforge-api")))
}